Compilador.WebApp/Models/ErrorViewModel.cs
using System;

namespace Compilador.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Compilador.WebApp/Models/FileViewModel.cs
namespace Compilador.WebApp.Models
{
    public class FileViewModel
    {
       
        public string FileFullPath { get; set; }
        
    }
}

Compilador.WebApp/Controllers/AnalisadorController.cs
using Compilador.WebApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IO;

namespace Compilador.WebApp.Controllers
{
    public class AnalisadorController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetFile(IFormFile FileFullPath, string fullText)
        {
            var filePath = Path.GetTempFileName();

            if(FileFullPath != null)
            {
                using (var stream = System.IO.File.Create(filePath))
                {
                    // The formFile is the method parameter which type is IFormFile
                    // Saves the files to the local file system using a file name generated by the app.
                    FileFullPath.CopyTo(stream);
                }

            }

            FileViewModel data = new FileViewModel()
            {
                FileFullPath = filePath,
            };

            return RedirectToAction("LerCodigo", "LerArquivo", data);
        }
    }
}

Compilador.WebApp/Controllers/LerArquivoController.cs
using System;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Compilador.Dominio;
using Compilador.WebApp.Models;
using Antlr4.Runtime;
using Antlr4.Runtime.Tree;
using Compilador.Dominio.Parser;

namespace Compilador.WebApp.Controllers
{
    public class LerArquivoController : Controller
    {
        private IWebHostEnvironment Environment;

        public LerArquivoController(IWebHostEnvironment _environment)
        {
            Environment = _environment;
        }

        public IActionResult LerCodigo(FileViewModel file)
        {
            AnaliseLexica analisadorLexico = new AnaliseLexica();

            string caminhoCodigo2 = file.FileFullPath;

            if (!System.IO.File.Exists(caminhoCodigo2))
            {
                ViewBag.Data = string.Empty;
                return View();
            }

            IEnumerable<string> lines = System.IO.File.ReadLines(caminhoCodigo2);

            List<GeradorItemsLexicos> listAnalisador = new();

            foreach (var line in lines)
            {
                if (string.IsNullOrEmpty(line))
                {
                    continue;
                }

                List<char> linha = line.ToList();

                listAnalisador.AddRange(analisadorLexico.Analisador(linha));
            }

            List<string> textsList = new List<string>();
            List<GeradorItemsSintaticos> itemsSintaticos = new List<GeradorItemsSintaticos>();

            for (int i = 0; i < listAnalisador.Count; i++)
            {
                textsList.Add(listAnalisador[i].ToString());
                if (listAnalisador[i].Token.Contains(',') && listAnalisador[i].Token != ",") {
                    var tokenFiltrado = listAnalisador[i].Token.Split(',')[0];
                    itemsSintaticos.Add(new GeradorItemsSintaticos(tokenFiltrado));
                }
                else
                    itemsSintaticos.Add(new GeradorItemsSintaticos(listAnalisador[i].Token));
            }

            string stream = "";

            foreach (var item in itemsSintaticos)
            {
                stream += item + "\r\n";
            }

            var inputStream = new AntlrInputStream(stream);

            var languageLexer = new LanguageLexer(inputStream);

            var commonTokenStream = new CommonTokenStream(languageLexer);

            var languageParser = new LanguageParser(commonTokenStream);

            LanguageErrorListener errorListener;
            
            StringWriter writer = new StringWriter();
            errorListener = new LanguageErrorListener(writer);
            
            languageParser.RemoveErrorListeners();
            languageParser.AddErrorListener(errorListener);

            languageParser.program();

            string retornoSintatico = "";
            if(languageParser.NumberOfSyntaxErrors == 0)
                retornoSintatico += "Código válido";
            else
            {
                retornoSintatico += "Erro: " + errorListener.Writer + "\r\n";
            }
            
            string[] listaTokens = textsList.ToArray();
            List<object> retornos = new List<object>();
            retornos.Add(listaTokens);
            retornos.Add(retornoSintatico);

            ViewBag.Data = retornos;
            return View();

        }
    }
}

Compilador.WebApp/Views/Analisador/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
 
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Analisador</title>
</head>
<body>

     <form method="post" enctype="multipart/form-data" asp-controller="Analisador" asp-action="GetFile">
        <span>Selecione o arquivo:</span>

        <input type="file" id="myFile" name="FileFullPath"/>
        <br/>
        <br/>
        <input type="submit" value="Ler arquivo"></input>

       <h1> </h1>
    </form>
    <br/>

    

</body>
</html>

Compilador.WebApp/Views/LerArquivo/LerCodigo.cshtml
@{
    ViewData["Title"] = "Arquivo lido";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
    <body>
        <div>
            <table style="width:100%">
                @if (ViewBag.Data[0].Length < 1 || ViewBag.Data == null)
                {
                    <tr>
                        <td>A lista de tokens não conseguiu ser gerada...</td>
                    </tr>
                }
                else
                {
                    <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#analise_sintatica">Resultado Análise Sintática</button>
                    <div id="analise_sintatica" class="collapse">
                        @if (ViewBag.Data[1] == "Código válido")
                        {
                            <h1 style="color: darkgreen">Código sintáticamente válido</h1>
                        }
                        else
                        {
                            <h1 style="color: red">Código sintáticamente inválido</h1>
                            <h2 style="color: red">@ViewBag.Data[1]</h2>
                        }
                    </div>
                    
                    <br />
                    <br />
                    
                    <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#analise_lexica">Resultado Análise Léxica</button>
                    <tr id="analise_lexica" class="collapse">
                        <th>Lexema</th>
                        <th>Token</th>
                        <th>Símbolo</th>
                    </tr>
                    @foreach (string text in ViewBag.Data[0])
                    {
                        string val0 = text.Split(@"\")[0];
                        string val1 = text.Split(@"\")[1];
                        string val2 = text.Split(@"\")[2];
                        @if (val1 == "ERRO")
                        {
                            <tr style="color:red" id="analise_lexica" class="collapse">
                                <td>@val0</td>
                                <td>@val1</td>
                                <td>@val2</td>
                            </tr>
                        }
                        else
                        {
                            <tr id="analise_lexica" class="collapse">
                                <td>@val0</td>
                                <td>@val1</td>
                                <td>@val2</td>
                            </tr>
                        }
                    }
                }
            </table>
        </div>
    </body>
</html>

Compilador.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Compilador.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Analisador" asp-action="Index">Compilador.WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Analisador" asp-action="Index">Analisador</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Compilador.WebApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>